spring:
  application:
    name: spring-boot-redis-cluster-practice
  data:
    redis:
      cluster:
        nodes:
          - 10.1.201.98:7000
          - 10.1.201.98:7001
          - 10.1.201.98:7002
          - 10.1.201.98:7003
          - 10.1.201.98:7004
          - 10.1.201.98:7005
      password: pass.123
