spring:
  application:
    name: spring-boot-redis-cluster-practice
  config:
    import: classpath:ip.properties
  data:
    redis:
      cluster:
        nodes:
          - ${ip}:7000
          - ${ip}:7001
          - ${ip}:7002
          - ${ip}:7003
          - ${ip}:7004
          - ${ip}:7005
      password: ${redis.password}


